modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/bigenergy/achievement-optimizer/issues"
license = "MIT"

[[mods]]
modId = "achiopt"
version = "${version}"
displayName = "AchievementOptimizer"
authors = "Big_Energy"
description = '''
Performance optimizer for Achievements
'''
#logoFile = ""

[[dependencies.achiopt]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.achiopt]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.achiopt]]
modId = "architectury"
type = "required"
versionRange = "[18.0.5,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "achiopt.mixins.json"
